### ISSUE TITLE
about the LUTs

### ISSUE THREAD

**Issue by semchan** [VITA-Group/SSHarmonization#4]
great work!!! I have a question about the LUTs: "Given one input image, there exist hundreds of LUTs that can be applied to generate its stylized versions and dramatically enrich the training data", is that mean, there are "hundreds of LUTs" templates for you to process the images during the training phase?  if yes, where can I get these LUTs? thanks a lot.

**Comment by junleen** [comment]
您好，这是来自QQ邮箱的自动回复邮件。我将尽快阅读您的邮件，谢谢！

**Comment by yueruchen** [comment]
Yes, there are 100 LUTs used in this work. Due to some commercial issue those LUTs are owned by Adobe Inc. and can not be shared. But I believe you can get similar performance by collecting some LUTs from website, like https://www.rocketstock.com/free-after-effects-templates/35-free-luts-for-color-grading-videos/

**Comment by semchan** [comment]
> Yes, there are 100 LUTs used in this work. Due to some commercial issue those LUTs are owned by Adobe Inc. and can not be shared. But I believe you can get similar performance by collecting some LUTs from website, like https://www.rocketstock.com/free-after-effects-templates/35-free-luts-for-color-grading-videos/
 Got it and thanks very much.
